export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const GET_BY_USER_DATA = "GET_BY_USER_DATA";

export const MINT_SUCCESS = "MINT_SUCCESS";
export const MINT_REQUEST = "MINT_REQUEST";
export const GET_PREVIOUS_URL = "GET_PREVIOUS_URL";
export const SET_PREVIOUS_URL = "SET_PREVIOUS_URL";
export const CHECKED_REMEMBER_ME = "CHECKED_REMEMBER_ME";
export const UN_CHECKED_REMEMBER_ME = "UN_CHECKED_REMEMBER_ME";
export const SET_PRODUCT_TAB_KEY = "SET_PRODUCT_TAB_KEY";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";